### ISSUE TITLE
Allow custom database.yml without activerecord

### ISSUE THREAD

**Issue by JacobEvelyn** [heroku/heroku-buildpack-ruby#1278]
We have a Rails app that uses the `sequel` gem instead of `activerecord`. Currently, Heroku's buildpack [requires](https://github.com/heroku/heroku-buildpack-ruby/blob/cdc7902735b512ade68561de752f31c611f39ba0/lib/language_pack/ruby.rb#L896) us to put `activerecord` in our `Gemfile` so that our `config/database.yml` isn't overwritten.

Is there a way this could be changed so that we can remove `activerecord` from our `Gemfile`? I assume checking for the existence of `config/database.yml` is problematic for some other reason, but maybe there could be an opt-in flag we could pass, or the buildpack could detect the presence of the `sequel` gem?

**Comment by schneems** [comment]
https://devcenter.heroku.com/articles/rails-database-connection-behavior

**Comment by JacobEvelyn** [comment]
Hi @schneems—I might be missing something but I don't think that documentation helps. The documentation is Active Record-specific, as is the behavior I linked to in the buildpack, but we don't use the `activerecord` gem so our `config/database.yml` file is getting overwritten instead of merged. Does that make sense?

**Comment by JacobEvelyn** [comment]
For context, our `config/database.yml` file has these settings that `sequel` can use:

```yml
production:
  adapter: <%= OurApp.connect_to_db? ? 'postgresql' : 'mock' %>
<% if OurApp.use_ssl? %>
  sslmode: require
<% end %>
  url: <%= OurApp.connect_to_db? ? ENV["DATABASE_URL"] : 'mock://' %>
  prepared_statements: false # Allows the use of Heroku connection pooling via PgBouncer
<% if OurApp.use_read_replicas? %>
  servers:
    read_only:
      host: <%= OurApp.random_follower_host_name %>
<% end %>
```
