### ISSUE TITLE
database.yml missing options

### ISSUE THREAD

**Issue by nicka** [heroku/heroku-buildpack-ruby#299]
What would happen to the `encoding` and `collation` options from a `database.yml`?

For example i would like to set:
```
production:
  ...
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
```
